---
# tasks file for tomcat

- name: install JDK
  yum:
    name: java
    state: latest

- name: install tomcat
  yum:
    name: tomcat
    state: latest
- name: install adiitional package
  yum:
    name:
      - tomcat-webapps
      - tomcat-admin-webapps
      - tomcat-docs-webapp
    state: installed
    
- name: copy tomcat-users.xml
  copy:
    src: tomcat-users.xml
    dest: /usr/share/tomcat/conf/tomcat-users.xml

- name: start the server
  service:
    name: tomcat
    state: started
